# Define variables for project ID, image name, and tag.
# Customize these values as needed.
substitutions:
  _PROJECT_ID: 'project-pic-cloudap'  # Replace with your actual project ID.
  _IMAGE_NAME: 'gcr.io/${_PROJECT_ID}/my-app'
  _TAG_NAME: '0.0.1'
  _REGION: 'asia-east1'  # Replace with your preferred region.
  _SERVICE_NAME: 'wilson-test-gcp-cicd-service'  # Replace with your preferred Cloud Run service name.

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}:${_TAG_NAME}', '.']

# Push the Docker image to Google Container Registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}:${_TAG_NAME}']

# Deploy to Cloud Run.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image=${_IMAGE_NAME}:${_TAG_NAME}'
  - '--platform=managed'
  - '--region=${_REGION}'

images:
- '${_IMAGE_NAME}:${_TAG_NAME}'  # Reference the dynamic image name and tag.
